/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS_IServices.IQLOrder_Service;
import BUS_Services.QLOrder_Service;
import DAL_Models.ENTITY_Area;
import DAL_Models.ENTITY_BILL;
import Utils.dateHelper;
import Utils.dialogHelper;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.net.URL;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author phamd
 */
public class GUI_QL_Order extends javax.swing.JDialog {

    private IQLOrder_Service qlod;
    private NumberFormat n = new DecimalFormat("#,###");
    private DefaultTableModel modell;
    private int dong = 0;

    /**
     * Creates new form GUI_QL_Order
     */
    public GUI_QL_Order(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    private void init() {
        this.setSize(1400, 1000);
        this.qlod = (IQLOrder_Service) new QLOrder_Service();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbbKhu.getModel(); //kết nối cbo với model
        this.modell = (DefaultTableModel) this.tblOrder.getModel();
        model.removeAllElements(); //xóa toàn bộ item
        this.qlod.hienTableOder(tblOrder);
        try {
            //lấy tất cả đối tượng nguoiHoc không thuộc khoaHoc từ CSDL
            //rồi thêm vào combobox
            ArrayList<ENTITY_Area> list = this.qlod.getkhu();
            for (ENTITY_Area nh : list) {
                model.addElement(nh);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        this.tblSanPham.setName("SP");
        this.tblOrder.setName("Oder");
        this.qlod.hienTableSP(this.tblSanPham);
        this.txtmaHD.setEditable(false);
        this.txtNameEMP.setEditable(false);
        this.txtTong.setEditable(false);
        this.txtTienThua.setEditable(false);
        tblSanPham.getColumnModel().getColumn(5).setCellRenderer(new ClientsTableButtonRenderer());
        tblSanPham.getColumnModel().getColumn(5).setCellEditor(new ClientsTableRenderer(new JCheckBox()));
        tblSanPham.setPreferredScrollableViewportSize(tblSanPham.getPreferredSize());
        tblOrder.getColumnModel().getColumn(6).setCellRenderer(new ClientsTableButtonRenderer());
        tblOrder.getColumnModel().getColumn(6).setCellEditor(new ClientsTableRenderer(new JCheckBox()));
        tblOrder.setPreferredScrollableViewportSize(tblOrder.getPreferredSize());
        CardLayout card = (CardLayout) PanCac.getLayout();
        card.show(PanCac, "card2");
        this.lblNgay.setText(this.lblNgay.getText() + dateHelper.DATE_FORMATER.format(dateHelper.now()));
        tblOrder.setRowHeight(30);
        tblSanPham.setRowHeight(30);
        tblSanPham.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.RED));        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmnOder = new javax.swing.JPopupMenu();
        mnHuymon = new javax.swing.JMenuItem();
        pmmBtn = new javax.swing.JPopupMenu();
        mnChuyenBan = new javax.swing.JMenuItem();
        mnGopBan = new javax.swing.JMenuItem();
        mnXoaBan = new javax.swing.JMenuItem();
        Fom = new javax.swing.JPanel();
        btnxemlichsu = new javax.swing.JButton();
        btnVaoBan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbbKhu = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PanSanPham = new javax.swing.JPanel();
        txtTim = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        PanCac = new javax.swing.JPanel();
        PanLichSu = new javax.swing.JPanel();
        lblNgay = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLichSu = new javax.swing.JTable();
        PanOrder = new javax.swing.JPanel();
        txtMaKH = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtmaHD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblBan = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtTong = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JButton();
        btnLuuVSIn = new javax.swing.JButton();
        btnTachHD = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTienTra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTienThua = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNameEMP = new javax.swing.JTextField();
        btnguowi = new javax.swing.JButton();

        mnHuymon.setText("Hủy món");
        mnHuymon.setToolTipText("");
        mnHuymon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnHuymonMouseClicked(evt);
            }
        });
        pmnOder.add(mnHuymon);

        mnChuyenBan.setBackground(new java.awt.Color(255, 204, 102));
        mnChuyenBan.setText("Chuyển bàn");
        mnChuyenBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnChuyenBanActionPerformed(evt);
            }
        });
        pmmBtn.add(mnChuyenBan);

        mnGopBan.setBackground(new java.awt.Color(255, 204, 102));
        mnGopBan.setText("Gộp bàn");
        mnGopBan.setToolTipText("");
        pmmBtn.add(mnGopBan);

        mnXoaBan.setBackground(new java.awt.Color(255, 204, 102));
        mnXoaBan.setText("Xóa bàn");
        pmmBtn.add(mnXoaBan);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 51));

        Fom.setBackground(new java.awt.Color(153, 255, 255));
        Fom.setPreferredSize(new java.awt.Dimension(1300, 613));

        btnxemlichsu.setBackground(new java.awt.Color(255, 102, 51));
        btnxemlichsu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnxemlichsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/lichsu.png"))); // NOI18N
        btnxemlichsu.setText("lịch sử Order");
        btnxemlichsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxemlichsuActionPerformed(evt);
            }
        });

        btnVaoBan.setBackground(new java.awt.Color(0, 255, 0));
        btnVaoBan.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVaoBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/vaoban.png"))); // NOI18N
        btnVaoBan.setText("Vào bàn");
        btnVaoBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaoBanActionPerformed(evt);
            }
        });

        jLabel2.setText("Khu vực");

        cbbKhu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbKhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbKhuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Chào mừng bạn đến với SanFasico");

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        PanSanPham.setBackground(new java.awt.Color(255, 102, 255));
        PanSanPham.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách sản phẩm"));

        txtTim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTimKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Zoom-icon.png"))); // NOI18N
        jLabel9.setText("Tìm Kiếm");

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblSanPham);

        javax.swing.GroupLayout PanSanPhamLayout = new javax.swing.GroupLayout(PanSanPham);
        PanSanPham.setLayout(PanSanPhamLayout);
        PanSanPhamLayout.setHorizontalGroup(
            PanSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanSanPhamLayout.createSequentialGroup()
                .addGroup(PanSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanSanPhamLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTim))
                    .addGroup(PanSanPhamLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
        );
        PanSanPhamLayout.setVerticalGroup(
            PanSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanSanPhamLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        PanCac.setForeground(new java.awt.Color(153, 255, 153));
        PanCac.setLayout(new java.awt.CardLayout());

        PanLichSu.setBackground(new java.awt.Color(255, 204, 204));
        PanLichSu.setBorder(javax.swing.BorderFactory.createTitledBorder("Lịch sử Order"));
        PanLichSu.setForeground(new java.awt.Color(102, 255, 102));

        lblNgay.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNgay.setText("Lịch sử Oder ngày : ");

        tblLichSu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDOrder", "TimeOrder", "Name NV", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLichSu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLichSuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLichSu);

        javax.swing.GroupLayout PanLichSuLayout = new javax.swing.GroupLayout(PanLichSu);
        PanLichSu.setLayout(PanLichSuLayout);
        PanLichSuLayout.setHorizontalGroup(
            PanLichSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanLichSuLayout.createSequentialGroup()
                .addGroup(PanLichSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanLichSuLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(lblNgay))
                    .addGroup(PanLichSuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        PanLichSuLayout.setVerticalGroup(
            PanLichSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanLichSuLayout.createSequentialGroup()
                .addComponent(lblNgay)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanCac.add(PanLichSu, "card2");

        PanOrder.setBackground(new java.awt.Color(255, 255, 153));
        PanOrder.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Order"));
        PanOrder.setForeground(new java.awt.Color(153, 255, 51));

        jLabel6.setText("Mã KH");

        jLabel5.setText("Mã HĐ");

        lblBan.setText("000");

        jLabel3.setText("Bàn");

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDOrder", "TimeOrder", "Name NV", "Status", "Title 5", "Title 6", "Title 7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblOrderMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrder);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Tổng tiền");

        txtTong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnThanhToan.setBackground(new java.awt.Color(51, 153, 0));
        btnThanhToan.setForeground(new java.awt.Color(0, 0, 0));
        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Cash-register-icon.png"))); // NOI18N
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnLuuVSIn.setBackground(new java.awt.Color(255, 204, 51));
        btnLuuVSIn.setForeground(new java.awt.Color(0, 0, 0));
        btnLuuVSIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/luuhoadon.png"))); // NOI18N
        btnLuuVSIn.setText("Lưu và In HĐ");
        btnLuuVSIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuVSInActionPerformed(evt);
            }
        });

        btnTachHD.setBackground(new java.awt.Color(255, 102, 51));
        btnTachHD.setForeground(new java.awt.Color(0, 0, 0));
        btnTachHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/tachHD.png"))); // NOI18N
        btnTachHD.setText("Tách HĐ");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Tiền khách trả");

        txtTienTra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTienTraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTienTraKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("Tiền thừa");

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Button-Close-icon.png"))); // NOI18N
        jButton1.setText("Hủy HĐ");

        jLabel10.setText("Time Order");

        lblTime.setText("12:12 PM");

        jLabel12.setText("Nhân viên Order :");

        btnguowi.setBackground(new java.awt.Color(255, 102, 51));
        btnguowi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnguowi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/order-icon.png"))); // NOI18N
        btnguowi.setText("Gửi Order");
        btnguowi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnguowi.setDefaultCapable(false);
        btnguowi.setFocusable(false);
        btnguowi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguowiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanOrderLayout = new javax.swing.GroupLayout(PanOrder);
        PanOrder.setLayout(PanOrderLayout);
        PanOrderLayout.setHorizontalGroup(
            PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanOrderLayout.createSequentialGroup()
                        .addGroup(PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanOrderLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lblBan)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtmaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanOrderLayout.createSequentialGroup()
                                .addGroup(PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanOrderLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(23, 23, 23)
                                        .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanOrderLayout.createSequentialGroup()
                                        .addGroup(PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTienTra)
                                            .addComponent(txtTienThua))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnguowi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnTachHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLuuVSIn))))
                        .addGroup(PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanOrderLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnThanhToan))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanOrderLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(lblTime))))
                    .addGroup(PanOrderLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNameEMP, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        PanOrderLayout.setVerticalGroup(
            PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanOrderLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblBan)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtmaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(lblTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNameEMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanOrderLayout.createSequentialGroup()
                        .addGroup(PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTienTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanOrderLayout.createSequentialGroup()
                            .addGroup(PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnLuuVSIn)
                                .addComponent(jButton1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(PanOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnTachHD)
                                .addComponent(btnguowi)))))
                .addContainerGap())
        );

        PanCac.add(PanOrder, "card3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanSanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(PanCac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanCac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout FomLayout = new javax.swing.GroupLayout(Fom);
        Fom.setLayout(FomLayout);
        FomLayout.setHorizontalGroup(
            FomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FomLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(FomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FomLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(cbbKhu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FomLayout.createSequentialGroup()
                        .addComponent(btnVaoBan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnxemlichsu))
                    .addGroup(FomLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        FomLayout.setVerticalGroup(
            FomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FomLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(19, 19, 19)
                        .addGroup(FomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbbKhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(FomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVaoBan)
                            .addComponent(btnxemlichsu)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fom, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        Fom.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVaoBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaoBanActionPerformed
        // TODO add your handling code here:
        qlod.taoHD(txtmaHD);
        this.btnVaoBan.setVisible(false);
        this.PanOrder.setVisible(true);
        this.PanLichSu.setVisible(false);
    }//GEN-LAST:event_btnVaoBanActionPerformed
    private void goiTaoBan(ENTITY_Area khu) {
        this.qlod.taoTable(Fom, this, khu.getIDArea(), this.btnVaoBan, lblBan, tblOrder, tblLichSu, PanLichSu, PanOrder, txtmaHD, txtMaKH, txtNameEMP, lblTime,pmmBtn,txtTong);
    }
    private void cbbKhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbKhuActionPerformed
        // TODO add your handling code here:
        this.btnVaoBan.setVisible(false);
        ENTITY_Area ar = (ENTITY_Area) this.cbbKhu.getSelectedItem();
        if (ar != null) {
            goiTaoBan(ar);
        }
    }//GEN-LAST:event_cbbKhuActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        qlod.updatebn();
        qlod.thanhToan(txtmaHD);
        ENTITY_Area khu = (ENTITY_Area) cbbKhu.getSelectedItem();
        goiTaoBan(khu);
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void txtTimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKeyTyped
        // TODO add your handling code here:
        qlod.timSP(txtTim, tblSanPham);
    }//GEN-LAST:event_txtTimKeyTyped

    private void btnxemlichsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxemlichsuActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) PanCac.getLayout();
        card.show(PanCac, "card2");
        qlod.lichsuOrder(PanLichSu, tblLichSu);
    }//GEN-LAST:event_btnxemlichsuActionPerformed

    private void btnguowiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguowiActionPerformed
        // TODO add your handling code here:  
        int e = 0;
        if (this.txtNameEMP.getText().equals("") && this.modell.getRowCount() - qlod.dongC() != 0) {
            qlod.insertOr(txtmaHD);
        }
        for (int i = qlod.dongC(); i < this.modell.getRowCount(); i++) {
            ENTITY_BILL bill = new ENTITY_BILL();
            bill.setIDOrder(this.txtmaHD.getText());
            bill.setIDProduct(this.tblOrder.getValueAt(i, 0).toString());
            bill.setIDTable(this.lblBan.getText());
            bill.setNote(this.tblOrder.getValueAt(i, 5).toString());
            bill.setQuantity(Integer.valueOf(this.tblOrder.getValueAt(i, 4).toString()));
            bill.setReason("");
            qlod.insertOderDe(bill);
            e++;
        }
        if (e > 0) {
            qlod.updatebn();
        }
        ENTITY_Area khu = (ENTITY_Area) cbbKhu.getSelectedItem();
        goiTaoBan(khu);
    }//GEN-LAST:event_btnguowiActionPerformed

    private void btnLuuVSInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuVSInActionPerformed
        // TODO add your handling code here:
        try {            
            try (Writer b = new BufferedWriter(new OutputStreamWriter(new FileOutputStream("History.txt"), "UTF8"))) {
                b.write("\t\t\t\tSanfrancisco Coffee\r\n\r\n");
                b.write("\t\tĐịa chỉ: Tổ 4, P.Cự Khối, Q.Long Biên, Hà Nội\r\n");
                b.write("\t\tSĐT: 091 323 40 38\r\n");
                b.write("\t\tMã hóa đơn :"+txtmaHD.getText()+"\r\n");
                b.write("\t\tThời gian: " + lblTime.getText().trim() + " "+dateHelper.DATE_FORMATER.format(dateHelper.now())+"\r\n\r\n");
                b.write("\t\tNhân viên :"+txtNameEMP.getText()+"\r\n");             
                b.write("\t-------------------------------------------------------------------------------\r\n");
                b.write("\tMã SP\tSố lượng(ly)\tĐơn giá         Thời gian\tThành tiền(VNĐ)\r\n");
                b.write("\t-------------------------------------------------------------------------------\r\n");
                int line = tblOrder.getRowCount();
                for (int i = 0; i < line; i++) {
                    String n1 = (String) tblOrder.getValueAt(i, 0);
                    String n2 = (String) tblOrder.getValueAt(i, 1);
                    int n3 = (int) tblOrder.getValueAt(i, 2);
                    String n4 = (String) tblOrder.getValueAt(i, 3);
                    String n5 = (String) tblOrder.getValueAt(i, 4);
                    String n6 = (String) tblOrder.getValueAt(i, 7);
                    b.write("\t" + n1 + "\t" + n2 + "\t" + n3 + "\t\t" + n4 + "          " + n5 + "\t" + n6 + "\r\n");
                }
                b.write("\t-------------------------------------------------------------------------------\r\n");
                b.write("\tTổng tiền: " + txtTong.getText());
            }
        } catch (HeadlessException | IOException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        //Mở file txt
        Runtime runtime = Runtime.getRuntime();
        try {
            runtime.exec("notepad History.txt");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnLuuVSInActionPerformed

    private void tblLichSuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLichSuMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            txtmaHD.setText(tblLichSu.getValueAt(tblLichSu.getSelectedRow(), 0).toString());
            qlod.bill(txtmaHD, txtNameEMP, txtMaKH, lblTime, tblOrder);
            CardLayout card = (CardLayout) PanCac.getLayout();
            card.show(PanCac, "card3");
        }
    }//GEN-LAST:event_tblLichSuMouseClicked

    private void txtTienTraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienTraKeyTyped
        // TODO add your handling code here:
        Total();
    }//GEN-LAST:event_txtTienTraKeyTyped

    private void txtTienTraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienTraKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n') {
            Total();
            double tra = Double.parseDouble(txtTienTra.getText());
            double tong = Total();
            txtTienTra.setText(tra + "VNĐ");
            txtTienThua.setText(tra - tong + "VNĐ");
        }

    }//GEN-LAST:event_txtTienTraKeyPressed
    
    private void tblOrderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrderMouseReleased
        // TODO add your handling code here:        
        int r = tblOrder.rowAtPoint(evt.getPoint());
        if (r >= 0 && r < tblOrder.getRowCount()) {
            tblOrder.setRowSelectionInterval(r, r);
        } else {
            tblOrder.clearSelection();
        }
        int rowindex = tblOrder.getSelectedRow();
        if (rowindex < 0||rowindex>=qlod.dongC())
            return;
        if (evt.isPopupTrigger() && evt.getComponent() instanceof JTable ) {   
            pmnOder.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblOrderMouseReleased

    private void mnHuymonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnHuymonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnHuymonMouseClicked

    private void mnChuyenBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnChuyenBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnChuyenBanActionPerformed
    public double Total() {
        double total = 0;
        int line = this.tblOrder.getRowCount();
        for (int i = 0; i < line; i++) {
            double gia = Double.valueOf(this.tblOrder.getValueAt(i, 3).toString());
            int SL = Integer.valueOf(this.tblOrder.getValueAt(i, 4).toString());
            double thanhtien = gia * SL;
            total += thanhtien;
        }
        this.txtTong.setText(total + "VNĐ");
        return total;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_QL_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_QL_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_QL_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_QL_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI_QL_Order dialog = new GUI_QL_Order(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    class ClientsTableButtonRenderer extends JButton implements TableCellRenderer {

        public ClientsTableButtonRenderer() {
            setOpaque(true);
        }

        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            setForeground(Color.black);
            setBackground(UIManager.getColor("Button.background"));
//            setText((value == null) ? "" : value.toString());           
            setPreferredSize(new Dimension(40, 40));
            String s = value.toString();                       
            ClassLoader classLoader = this.getClass().getClassLoader();
            if (s.equals("Thêm")) {
                URL imagePath = classLoader.getResource("Icon/" + "add-cart" + ".png");
                Image imgBan = new ImageIcon(imagePath).getImage();
                Icon iconBan = new ImageIcon(imgBan.getScaledInstance(20, 20, imgBan.SCALE_SMOOTH));
                setIcon(iconBan);
            }
            if (s.equals("Xóa")) {
                URL imagePath = classLoader.getResource("Icon/" + "Button-Close-icon" + ".png");
                Image imgBan = new ImageIcon(imagePath).getImage();
                Icon iconBan = new ImageIcon(imgBan.getScaledInstance(20, 20, imgBan.SCALE_SMOOTH));
                setIcon(iconBan);
            }
            return this;
        }
    }

    public class ClientsTableRenderer extends DefaultCellEditor {

        private JButton button;
        private String label;
        private boolean clicked;
        private int row, col;
        private JTable table;

        public ClientsTableRenderer(JCheckBox checkBox) {
            super(checkBox);
            button = new JButton();
            button.setOpaque(true);
            button.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    fireEditingStopped();
                }
            });
        }

        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            this.table = table;
            this.row = row;
            this.col = column;
            button.setForeground(Color.black);
            button.setBackground(UIManager.getColor("Button.background"));
            label = (value == null) ? "" : value.toString();
//            button.setText(label);
            clicked = true;
            return button;
        }

        public Object getCellEditorValue() {
            if (clicked) {
                if (table.getName().equals("SP")) {
                    if (txtmaHD.getText().equals("")) {
                        dialogHelper.alert(PanSanPham, "Bố chưa vào bàn mà đòi thêm cái gì trời ?");
                    } else {
                        String n = null;
                        n = dialogHelper.prompt(PanSanPham, "Nhập vào số lượng sản phẩm");
                        if (n != null) {
                            Object[] row = {
                                tblSanPham.getValueAt(this.row, 0),
                                tblSanPham.getValueAt(this.row, 2),
                                tblSanPham.getValueAt(this.row, 3),
                                tblSanPham.getValueAt(this.row, 4),
                                n, "", "Xóa"
                            };
                            modell.addRow(row);
                            Total();
                        }
                    }
                } else {
                    if (this.row >= qlod.dongC()) {
                        modell.removeRow(this.row);
                        Total();
                    }
                }
            }
            clicked = false;
            return new String(label);
        }

        public boolean stopCellEditing() {
            clicked = false;
            return super.stopCellEditing();
        }

        protected void fireEditingStopped() {
            try {
                super.fireEditingStopped();
            } catch (ArrayIndexOutOfBoundsException e) {
                
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fom;
    private javax.swing.JPanel PanCac;
    private javax.swing.JPanel PanLichSu;
    private javax.swing.JPanel PanOrder;
    private javax.swing.JPanel PanSanPham;
    private javax.swing.JButton btnLuuVSIn;
    private javax.swing.JButton btnTachHD;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnVaoBan;
    private javax.swing.JButton btnguowi;
    private javax.swing.JButton btnxemlichsu;
    private javax.swing.JComboBox<String> cbbKhu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBan;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblTime;
    private javax.swing.JMenuItem mnChuyenBan;
    private javax.swing.JMenuItem mnGopBan;
    private javax.swing.JMenuItem mnHuymon;
    private javax.swing.JMenuItem mnXoaBan;
    private javax.swing.JPopupMenu pmmBtn;
    private javax.swing.JPopupMenu pmnOder;
    private javax.swing.JTable tblLichSu;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtNameEMP;
    private javax.swing.JTextField txtTienThua;
    private javax.swing.JTextField txtTienTra;
    private javax.swing.JTextField txtTim;
    private javax.swing.JTextField txtTong;
    private javax.swing.JTextField txtmaHD;
    // End of variables declaration//GEN-END:variables
}
